config/routes.rb
Rails.application.routes.draw do
  resources :simples
  resources :forms
  resources :pins
  root to:'pins#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/blob_validator.rb
class BlobValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, values)
      return unless values.attached?
  
      Array(values).each do |value|
        if options[:size_range].present?
          if options[:size_range].min > value.blob.byte_size
            record.errors.add(attribute, :min_size_error, min_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].min))
          elsif options[:size_range].max < value.blob.byte_size
            record.errors.add(attribute, :max_size_error, max_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].max))
          end
        end
  
        unless valid_content_type?(value.blob)
          record.errors.add(attribute, :content_type)
        end
      end
    end
  
    private
  
    def valid_content_type?(blob)
      return true if options[:content_type].nil?
  
      case options[:content_type]
      when Regexp
        options[:content_type].match?(blob.content_type)
      when Array
        options[:content_type].include?(blob.content_type)
      when Symbol
        blob.public_send("#{options[:content_type]}?")
      else
        options[:content_type] == blob.content_type
      end
    end
end

app/models/form.rb
class Form < ApplicationRecord
    validates :firstname ,:lastname, presence: true
end

app/models/pin.rb
class Pin < ApplicationRecord
  has_one_attached :image
  has_one_attached :file
  validates :title,presence: true
  validate :acceptable_image_type?

  def acceptable_image_type?
    return unless image.attached?
    return if image.content_type.in? ["image/png", "image/jpeg"]
    errors.add :image, "must be a PNG or JPG"
  end
  validate :acceptable_image_size?

  def acceptable_image_size?
    return unless image.attached?
    return unless image.byte_size > 5.kilobytes
    errors.add :image, "is over 5kB"
  end
  validate :check_file_type

  private

  def check_file_type
    if file.attached? && !file.content_type.in?(%w(application/msword application/pdf application/vnd.openxmlformats-officedocument.wordprocessingml.document application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet text/plain))
      file.purge # delete the uploaded file
      errors.add(:file, 'Must be any of one PDF,  DOC , DOCX , XLS , XLSX ,TEXT file')
    end
  end
  validate :acceptable_file_size?

  def acceptable_file_size?
      return unless file.attached?
      return unless file.byte_size > 100.kilobytes
      errors.add :file, "is over 100kB"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: %i[ show edit update destroy ]

  # GET /forms or /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1 or /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms or /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: "Form was successfully created." }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1 or /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: "Form was successfully updated." }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1 or /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: "Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_params
      params.require(:form).permit(:firstname, :lastname, :gender, :Are, :u, :eligible)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :caption,:image,:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/simples_helper.rb
module SimplesHelper
end

app/views/forms/_form.html.erb
<form action="/contactsave" class="contact_form" method="post">
      <label for="firstname">First Name</label>
      <input type="text" id="full_name" name="full_name" >
      <br><br>
      <label for="last name">Last Name</label>
      <input type="text" id="last_name" name="last_name" >
      <br><br>
      <label for="gender">gender</label>
      <input type="text" id="gender" name="gender" >
      <br><br>
      
      
      <input type="submit" value="Submit">
    </form>
    <!-- <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> -->
  </div>
</div>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Gender</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.firstname %></td>
        <td><%= form.lastname %></td>
        <td><%= form.gender %></td>
        
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @form.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @form.lastname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @form.gender %>
</p>

<p>
  <strong>Are:</strong>
  <%= @form.Are %>
</p>

<p>
  <strong>U:</strong>
  <%= @form.u %>
</p>

<p>
  <strong>Eligible:</strong>
  <%= @form.eligible %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Upload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="#">Entersoft </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a href="#" class ="navbar-brand" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pins <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "pins list", pins_path %></li>
                <li><%= link_to "New", new_pin_path %></li>
              </ul>
            </li>
            
          </ul>
        </div>
      </nav>
      <%= yield %>
      <br>    


  </body>
</html>

app/views/pins/_form.html.erb
<div class ="container">
  <%= form_with(model: pin, local: true) do |form| %>
    <% if pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :title %><br>
        <%= form.text_field :title,class:"form-control" %>
      </div>
    </div>
      
    <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :caption %><br>
        <%= form.text_area :caption,class:"form-control" %>
      </div>
    </div>
    <div class ="row">
      <div  class="form-group col-md-4">
        <%= form.label :image %>
        <%= form.file_field :image%>
      </div>
    </div>
    <div class ="row">
      <div class="form-group col-md-4">
        <%= form.label :file %>
        <%= form.file_field :file,direct_upload: true, 
        accept: 'application/pdf, 
        application/zip,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msexcel' %>
      </div>
    </div>
    <br>
    <div class ="row">
      <div class="actions">
        <%= form.submit 'Create', class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/pins/edit.html.erb
<div class ="container">
	<h1>Editing Pin</h1>

	<%= render 'form', pin: @pin %>
	<br>
	<%= link_to 'Show', @pin ,class:"btn btn-info"%> |
	<%= link_to 'Back', pins_path,class:"btn btn-warning" %>
</div>

app/views/pins/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Pins</h1>

<div class="pin-block">  
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-1">Title</th>
        <th class="col-md-1">Caption</th>        
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pins.each do |pin| %>
        <tr>
          <td class="col-md-1"><%= pin.title %></td>
          <td class="col-md-1"><%= pin.caption %></td>
          <td class="col-md-2">
            <%= link_to 'Show', pin, class: "btn btn-info" %>
            <%= link_to 'Edit', edit_pin_path(pin), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
  

  <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary" %>
 </div> 

app/views/pins/new.html.erb
<div class="container">
	<h1>New Pin</h1>

	<%= render 'form', pin: @pin %>
	<br><%= link_to 'Back', pins_path ,class:"btn btn-dark"%>
</div>

app/views/pins/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @pin.title %>
  </p> 

  <p>
    <strong>Caption:</strong>
    <%= @pin.caption %>
  </p>

  <div style="width:200px;height:auto">  
    <%=  image_tag(@pin.image,style: 'width:100%') %><br><%= link_to 'Downloadpicture',@pin.image,download: '',class:"btn btn-primary"%>
    
  </div>
  <br>
  <div >
    <%=link_to 'veiwFile',@pin.file,class: "btn btn-default"%>
    <%=link_to 'DownloadFile',@pin.file,download:'',class:"btn btn-primary" %> 
  </div>
  <br>  

  <%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-warning" %> |
  <%= link_to 'Back', pins_path,class: "btn btn-dark" %>
</div>